#!/usr/bin/python

import sys

colors = ["0;30","1;30","0;31","1;31","0;32","1;32","0;33","1;33","0;34","1;34","0;35","1;35","0;36","1;36","0;37","1;37"]
stream = ""

for x in sys.stdin.readline().strip().split( )[0]:
    stream += f'\033[{colors[int(x,16)]}m█'

print(stream)
